Aviva.FizzBuzz/Aviva.FizzBuzz/Models/FizzBuzzModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using FizzBuzz.Model;

namespace Aviva.FizzBuzz.Models
{
     /// <summary>
    /// The view model for the Fizz Buzz Operation
    /// </summary>
    public class FizzBuzzModel
    {
        /// <summary>
        /// Default value of Page Size
        /// </summary>
        public const int PageSize = 20;

        public FizzBuzzModel()
        {
            Page = new Pagging();
        }

        /// <summary>
        /// Get or set Page to view pagging on ViewPage
        /// </summary>
        public Pagging Page { get; set; }

        int? nNumber;
        /// <summary>
        /// Gets or sets the input number.
        /// </summary>
        [Required]
        [Display(Name = "Please enter the number")]
        [Range(1, 1000, ErrorMessage = "Please enter a value between 1 and 1000")]
        public int? Number {
            get
            {
                return nNumber;
            }
            set
            {
                nNumber         = value;
                Page.PageIndex  = 1;
                Page.PageCount  = (Convert.ToInt32(nNumber) / PageSize);
                Page.PageCount  = ((nNumber % PageSize)) == 0 ? Page.PageCount : Page.PageCount + 1;
            }
        }

        /// <summary>
        /// Gets or sets the Division object list.
        /// </summary>
        public List<IFizzBuzz> FizzBuzzList { get; set; }        
    }
}

Aviva.FizzBuzz/Aviva.FizzBuzz/Models/Pagging.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Aviva.FizzBuzz.Models
{
    /// <summary>
    /// Pagging for have current pageIndex and PageCount
    /// </summary>
    public class Pagging
    {
        /// <summary>
        /// Set Default value in constructure
        /// </summary>
        public Pagging(){ 
            PageIndex = 1; 
        }

        /// <summary>
        /// Page index of the pagination.
        /// </summary>
        public int PageIndex { get; set; }

        /// <summary>
        /// Page count of the pagination.
        /// </summary>
        public int PageCount { get; set; }
    }
}

Aviva.FizzBuzz/Aviva.FizzBuzz/Controllers/FizzBuzzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using FizzBuzz.Model;
using Aviva.FizzBuzz.Common;
using Aviva.FizzBuzz.Models;
using System.Collections;
using StructureMap;

namespace Aviva.FizzBuzz.Controllers
{
    public class FizzBuzzController : Controller
    {
        private readonly IStrategic strategicLogic;
        private readonly IList<IFizzBuzz> fizzbuzz;

        /// <summary>
        /// Controller. Creates an instance of FizzBuzzController
        /// </summary>
        public FizzBuzzController(IStrategic StrategicLogic, IList<IFizzBuzz> FizzBuzz)
        {
            this.strategicLogic     = StrategicLogic;
            this.fizzbuzz           = FizzBuzz;
        }

        /// <summary>
        /// Action method to render the initial view.
        /// </summary>
        /// <returns>FizzBuzzView View</returns>
        [HttpGet]
        public ActionResult FizzBuzzView()
        {           
            return View("FizzBuzzView", new FizzBuzzModel());
        }

        /// <summary>
        /// Action method to render on Get Data button submit.
        /// </summary>
        /// <returns>FizzBuzzView View</returns>
        [HttpPost]
        [Button(ButtonName = "DisplayList")]
        [ActionName("FizzBuzzView")]
        public ActionResult FizzBuzzView(FizzBuzzModel PostModel)
        {
            FizzBuzzModel objData = new FizzBuzzModel() { Number = PostModel.Number };
            objData.Page.PageIndex = 1;

            if (ModelState.IsValid) { fillFizzBuzzList(objData); }
            TempData["FizzBuzzPage"] = objData.Page;
            return View("FizzBuzzView", objData);
        }

                /// <summary>
        /// Action method to render on Previous button click.
        /// </summary>
        /// <returns>FizzBuzzView View</returns>
        [HttpPost]
        [Button(ButtonName = "Previous")]
        [ActionName("FizzBuzzView")]
        public ActionResult FizzBuzzViewPrevious(FizzBuzzModel PostModel)
        {
            FizzBuzzModel objData   = new FizzBuzzModel() { Number = PostModel.Number };
            objData.Page            = (TempData["FizzBuzzPage"] != null) ? TempData["FizzBuzzPage"] as Pagging : new Pagging();
            objData.Page.PageIndex  = (objData.Page.PageIndex == 1) ? objData.Page.PageIndex : (objData.Page.PageIndex - 1);

            if (ModelState.IsValid) { fillFizzBuzzList(objData); }
            TempData["FizzBuzzPage"] = objData.Page;
            return View("FizzBuzzView", objData);
        }

        /// <summary>
        /// Action method to render on Next button click.
        /// </summary>
        /// <returns>FizzBuzzView View</returns>
        [HttpPost]
        [Button(ButtonName = "Next")]
        [ActionName("FizzBuzzView")]
        public ActionResult FizzBuzzViewNext(FizzBuzzModel PostModel)
        {
            FizzBuzzModel objData   = new FizzBuzzModel() { Number = PostModel.Number };
            objData.Page            = (TempData["FizzBuzzPage"] != null) ? TempData["FizzBuzzPage"] as Pagging : new Pagging();
            objData.Page.PageIndex  = (objData.Page.PageIndex == objData.Page.PageCount) ? objData.Page.PageIndex : (objData.Page.PageIndex + 1);

            if (ModelState.IsValid) { fillFizzBuzzList(objData); }
            TempData["FizzBuzzPage"] = objData.Page;
            return View("FizzBuzzView", objData);
        }

        private void fillFizzBuzzList(FizzBuzzModel objData)
        {
            objData.FizzBuzzList    = strategicLogic.GetList(objData.Number.Value, fizzbuzz);
            var startndex           = (objData.Page.PageIndex - 1) * FizzBuzzModel.PageSize;
            objData.FizzBuzzList    = objData.FizzBuzzList.GetRange(startndex, objData.Number.Value - startndex < FizzBuzzModel.PageSize ? objData.Number.Value - startndex : FizzBuzzModel.PageSize);
        }

    }
}

Aviva.FizzBuzz/Aviva.FizzBuzz/Views/FizzBuzz/FizzBuzzView.cshtml
@model Aviva.FizzBuzz.Models.FizzBuzzModel

@{
    ViewBag.Title = "FizzBuzz Application";
}
<h2>Input Screen</h2>
@using (Html.BeginForm("FizzBuzzView", "FizzBuzz"))
{
    <div>
        <fieldset>
            <table>
                <tr>
                    <td>
                        <div class="editor-label">
                            @Html.LabelFor(m => m.Number)
                        </div>
                    </td>
                    <td>
                        <div class="editor-field">
                            @Html.TextBoxFor(m => m.Number)
                            @Html.ValidationMessageFor(m => m.Number)
                        </div>
                    </td>
                    <td><input type="submit" name="DisplayList" value="Display List" /></td>
                </tr>
            </table>
        </fieldset>
    </div>

    if (Model.FizzBuzzList != null && Model.FizzBuzzList.Count > 0)
    {
        string NextButtonDisable = (Model.Page.PageIndex == Model.Page.PageCount) ? "disabled=\"disabled\"" : string.Empty;
        string PreviousButtonDisable = (Model.Page.PageIndex == 1) ? "disabled=\"disabled\"" : string.Empty;
        <div>
            <fieldset>
                <table>
                    <tr>
                        <td width="50%">
                            Showing Page <b>@Model.Page.PageIndex</b> of <b>@Model.Page.PageCount</b> Pages
                        </td>
                        <td width="50%" align="right">
                            <input type="submit" name="Previous" value="Previous" id="Previous" @PreviousButtonDisable />
                            <input type="submit" name="Next" value="Next" id="Next" @NextButtonDisable />
                        </td>
                    </tr>
                    @foreach (var number in Model.FizzBuzzList)
                    {
                        <tr>
                            <td colspan="2">
                                @if (string.IsNullOrEmpty(number.MessageColor))
                                {
                                    <div class="@number">@number.Message</div>
                                }
                                else
                                {
                                    <div style="color:@number.MessageColor" class="@number">@number.Message</div>
                                }
                            </td>
                        </tr>
                    }
                </table>
            </fieldset>
            <br />
        </div>
    }
}

Aviva.FizzBuzz/Aviva.FizzBuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>